### ISSUE TITLE
Change one of the projects

### ISSUE THREAD

**Issue by Bhavyaseth-afk** [Bhavyaseth-afk/Portfolio-BhavyaSeth#1]
I wish to replace my travelling project to one of my own projects only
The github code of the project is : https://github.com/Bhavyaseth-afk/kisanbackend

**Comment by Sanjana05mangal** [comment]
Hi. I think I can solve this issue, so please assign it to me.

**Comment by Bhavyaseth-afk** [comment]
Okay great!
Go ahead

**Comment by Sanjana05mangal** [comment]
While making the changes, should it be done within the same branch or I must create a new branch for it?

**Comment by Bhavyaseth-afk** [comment]
As you are the only working on the project you can push directly on the Master 
There is no need to create a different branch

Although If you wish to avoid merge conflicts 
Do make one!

**Comment by Bhavyaseth-afk** [comment]
Do let me know what you are looking forward to
Is it a new branch or not
You can surf if you wish?

**Comment by Sanjana05mangal** [comment]
Yes, I have created a new branch named "hello" so as to avoid the merge conflicts.
